### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by ivomarino** [stafwag/ansible-role-users#1]
Hello, would it be possible to also add  `shell` support so for example it would be possible to also define shells like `zsh` for an user? Thanks

**Comment by stafwag** [comment]
Yes. Was more or less already on my to-do list. 

A PR is also welcome :-)

**Comment by Solomonkassa** [comment]
check the manpage

**Comment by stafwag** [comment]
> check the manpage

@Solomonkassa Not sure what you're referring to... 

This is currently not implemented in this role. I'll implement it when I find some time. 

If somebody wants to implement it and create a PR this is also fine.

**Comment by stafwag** [comment]
> Hello, would it be possible to also add `shell` support so for example it would be possible to also define shells like `zsh` for an user? Thanks

**Comment by stafwag** [comment]
@ivomarino The shell parameter was added in the 1.2.0 release

Let me know if it works as expected. 
I'll close the issue if there no update within a week.

**Comment by ivomarino** [comment]
Thanks, great, will check asap

**Comment by stafwag** [comment]
@ivomarino Thx for your feature request. It's part of the official release. 

I'll close the issue.
